export const itemsArrayFixture = [
  {
    charName: "Wait",
    itemLocation: "a",
    itemName: "just",
    itemCount: "moment",
    charGuild: "please!",
  },
];

export const itemsArrayFixtureLarge = [
  {
    charName: "Minoldar",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Minoldar",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Minoldar",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Minoldar",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Minoldar",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Sharknado",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Sharknado",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Sharknado",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Sharknado",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Sharknado",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Machete",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Machete",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Machete",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Machete",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Machete",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Shivalry",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Grixus",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Penalty",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Work",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Work",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Work",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Work",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Work",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Zjil",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Zjil",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Zjil",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Zjil",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Zjil",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Faceoff",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Holo",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Holo",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Holo",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Holo",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Holo",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Exploder",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Exploder",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Exploder",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Exploder",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Lifesaver",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Lifesaver",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Lifesaver",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Lifesaver",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Lifesaver",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Captainn",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Captainn",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Captainn",
    charGuild: "Tempest",
    itemName: "Abashi",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Captainn",
    charGuild: "Tempest",
    itemName: "Crown of Rile",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Stork",
    charGuild: "Tempest",
    itemName: "Silver Charm of Tranquility",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Stork",
    charGuild: "Tempest",
    itemName: "Buckler of Insight",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Stork",
    charGuild: "Tempest",
    itemName: "Zlandicar's Heart",
    itemCount: "1",
    itemLocation: "Inventory",
  },
  {
    charName: "Stork",
    charGuild: "Tempest",
    itemName: "Robe of the Azure Sky",
    itemCount: "1",
    itemLocation: "Inventory",
  },
];

export const characterDropdownArray = ["ALL", "Grixus", "Stork", "Staypuft"];
